export const starterArr = [
  'Lviv',
  'Oregon',
  'Portland',
  'Cannon Beach',
  'Paris',
  'Colorado',
  'Alaska',
  'Fort Lauderdale',
  'San Francisco',
  'Juneau',
  'Dolores Park',
  'Yosemite',
  'Half Moon Bay',
  'Estes Park',
  'Seattle',
];
