export const starterArr = [
  'Lviv',
  'Oregon',
  'Cannon Beach',
  'Paris',
  'Colorado',
  'Alaska',
  'Fort Lauderdale',
  'San Francisco',
  'Juneau',
  'Dolores Park',
  'Yosemite',
  'Half Moon Bay',
  'Mt Hood',
  'Estes Park',
  'Seattle',
  'Wroclaw',
];
